const SUCCESS = "SUCCESS"
const FAILURE = "FAILURE"
const LOGIN_SUCCESS = "LOGIN_SUCCESS"
const LOGIN_FAILURE = "LOGIN_FAILURE"
const ADD_PROFILE = "ADD_PROFILE"
const REMOVE_PROFILE = "REMOVE_PROFILE"
const USER_INPUT_CHANGE = "USER_INPUT_CHANGE"
const USER_INPUT_SUBMIT = "USER_INPUT_SUBMIT"

export {
  SUCCESS, FAILURE, LOGIN_SUCCESS, LOGIN_FAILURE, ADD_PROFILE, REMOVE_PROFILE, USER_INPUT_CHANGE, USER_INPUT_SUBMIT
}