const SUCCESS = 'SUCCESS'
const FAILURE = 'FAILURE'
const USER_INPUT_CHANGE = 'USER_INPUT_CHANGE'
const USER_INPUT_SUBMIT = 'USER_INPUT_SUBMIT'

export { SUCCESS, FAILURE, USER_INPUT_CHANGE, USER_INPUT_SUBMIT }
